# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:
    desc: setup
    cmds:
      - |
        export LANG=C
        yes | yay -S \
          fish \
          ttf-meslo-nerd \
          neovim \
          neovide \
          git-delta \
          lazygit \
          xsel \
          xclip \
          firefox-tridactyl-native-bin
        mkdir -p ~/.config/konsave

  kde:
    desc: install kde
    cmds:
        - |
          yes | yay -S $(eos-packagelist KDE-Desktop)
          yes | yay -S stl-thumb-kde        

  sddm:
    desc: enable sddm login manager
    cmds:
      - systemctl disable gdm
      - systemctl enable sddm


  fish:
    desc: configure fish
    cmds:
      - |
        /usr/bin/fish
        curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
        fisher update
        fish_update_completions
        fisher install IlanCosman/tide@v6
        tide configure
        fisher install Asim-Tahir/docker-compose.fish
        fisher install edc/bass

  save:
    desc: save deafult profile
    cmds:
      - konsave -s default -f
      - konsave -e default -d /tmp

  load:
    desc: load profile from file
    cmds:
      - konsave -i {{.CLI_ARGS}}
      - konsave -a default

  ssh-agent:
    desc: enable ssh agent as service
    cmds:
      - |
        mkdir -p ~/.config/environment.d/
        echo 'SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"' > ~/.config/environment.d/ssh_auth_socket.conf
        systemctl --user enable --now ssh-agent

        grep -q  AddKeysToAgent  ~/.ssh/config || echo 'AddKeysToAgent  yes' >> ~/.ssh/config

  neovim:clean:
    desc: clean neovim config
    cmds:
      - rm -fR ~/.config/nvim
      - rm -fR ~/.local/*/nvim ~/.cache/nvim

  neovim:
    desc: setup neovim
    cmds:
      - sudo pacman -S --needed neovim unzip luarocks xclip wl-clipboard
      - git clone git@github.com:scipioni/nvim.git ~/.config/nvim && nvim 
      #- git clone https://github.com/LazyVim/starter ~/.config/nvim && nvim

  user-dir:
    desc: set home folders name
    cmds:
      - echo "en_US" > ~/.config/user-dirs.locale
      - xdg-user-dirs-update --force

  gnome:
    desc: customize gnome settings
    cmds:
      - dconf write /org/gnome/shell/extensions/pano/global-shortcut "['<Alt>v']"
