# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:
    desc: setup
    cmds:
      - |
        export LANG=C
        yes | yay -S \
          fish \
          plasma-workspace-agent-ssh \
          ttf-meslo-nerd \
          konsave
        mkdir -p ~/.config/konsave
        ln -sf ~/my-desktop/conf.yaml ~/.config/konsave/conf.yaml

  kde:
    desc: install kde
    cmds:
        - |
          yes | yay -S (eos-packagelist KDE-Desktop)
          yes | yay -S stl-thumb-kde        


  fish:
    desc: configure fish
    cmds:
      - |
        /usr/bin/fish
        curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
        fisher update
        fish_update_completions
        fisher install IlanCosman/tide@v6
        tide configure
        fisher install Asim-Tahir/docker-compose.fish

  save:
    desc: save deafult profile
    cmds:
      - konsave -s default -f
      - konsave -e default -d /tmp

  load:
    desc: load profile from file
    cmds:
      - konsave -i {{.CLI_ARGS}}
      - konsave -a default

  ssh-agent:
    desc: enable ssh agent as service
    cmds:
      - |
        mkdir -p ~/.config/environment.d/
        echo 'SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"' > ~/.config/environment.d/ssh_auth_socket.conf
        systemctl --user enable --now ssh-agent

        grep -q  AddKeysToAgent  ~/.ssh/config || echo 'AddKeysToAgent  yes' >> ~/.ssh/config

  neovim:
    desc: setup neovim
    cmds:
      - mkdir -p ~/.config/nvim
      - git clone https://github.com/NvChad/starter ~/.config/nvim && nvim 

